name: ContinuousIntegration
on: [push, workflow_dispatch]
jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - name: Get code
        uses: actions/checkout@v2.3.4
      - name: Install dependencies
        run: npm ci
      - name: Running linter
        run: npm run lint
  test:
    name: Running Tests
    runs-on: ubuntu-latest
    steps:
      - name: Get code
        uses: actions/checkout@v2.3.4
      - name: Install dependencies
        run: npm ci
      - name: Running tests
        run: npm run test
  build:
    name: Build
    runs-on: ubuntu-latest
    needs: [lint, test]
    steps:
      - name: Get code
        uses: actions/checkout@v2.3.4
      - name: Install dependencies
        run: npm ci
      - name: Building project
        run: npm run build
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Dummy Deployment
        run: echo "Deploying... please wait."