name: ContinuousIntegration
on: [push, workflow_dispatch]
jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - name: Get code
        uses: actions/checkout@v2.3.4
      - name: Install dependencies
        run: npm ci
      - name: Running linter
        run: npm run lint
