name: Issues
on: issues
jobs:
  issue:
    name: Issue
    runs-on: ubuntu-latest
    steps:
      - name: Issue
        run: echo "Issue n.${{ toJSON(github.event.issue.number) }} ${{ toJSON(github.event.action) }}"